#!/bin/bash
COOKIE_PATH="/tmp/.cookies.txt"
PATH="http://track.socek.org/rest"
LOGIN="api"
PASSWORD="$1"

WGET="/usr/bin/wget"
GREP="/bin/grep"
GIT="/usr/bin/git"
CUT="/usr/bin/cut"

$WGET --save-cookies $COOKIE_PATH \
     --post-data "login=${LOGIN}&password=${PASSWORD}" \
     ${PATH}/user/login \
     -qO-

TASKID=`${GIT} log -1 --pretty=%B | ${GREP} -o -E '#[-a-zA-Z0-9]+' | ${CUT} -c 2-`

if [ "$TASKID" != "" ] ; then

    $WGET --load-cookies $COOKIE_PATH \
        --post-data "command=done" \
        ${PATH}/issue/${TASKID}/execute \
        -qO-
fi
